export const ActionTypes = {
    SIGN_IN:"SIGN_IN",
    SIGN_OUT:"SIGN_OUT",
    CREATE_CATEGORY:"CREATE_CATEGORY",
    CATEGORY:"CATEGORY",
    GET_CATEGORY:"GET_CATEGORY",

    PRODUCTS:"PRODUCTS",
    PRODUCT:"PRODUCT",
}